"""Parse MacroFactor xlsx exports."""
from __future__ import annotations

import logging
import os
from typing import TypedDict

import openpyxl
import yaml

logger = logging.getLogger(__name__)


class FoodEntry(TypedDict):
    date: str
    time: str
    food_name: str
    serving_size: str
    serving_qty: float
    serving_weight_g: float
    total_weight_g: float
    calories_kcal: float
    protein_g: float
    fat_g: float
    carbs_g: float


# Column indices in the "Food Log" sheet (0-indexed)
_COL_DATE = 0
_COL_TIME = 1
_COL_FOOD_NAME = 2
_COL_SERVING_SIZE = 3
_COL_SERVING_QTY = 4
_COL_SERVING_WEIGHT_G = 5
_COL_CALORIES = 6
_COL_FAT = 7
_COL_CARBS = 8
_COL_PROTEIN = 9


def parse_food_log(xlsx_path: str) -> list[FoodEntry]:
    """Parse the 'Food Log' sheet from a MacroFactor export.

    Returns a list of FoodEntry dicts. Skips rows with no food name.
    """
    wb = openpyxl.load_workbook(xlsx_path, read_only=True)
    ws = wb["Food Log"]

    entries: list[FoodEntry] = []
    for row_idx, row in enumerate(ws.iter_rows(min_row=2, values_only=True), start=2):
        food_name = row[_COL_FOOD_NAME]
        if food_name is None or str(food_name).strip() == "":
            continue

        food_name = str(food_name).strip()
        serving_qty = float(row[_COL_SERVING_QTY] or 0)
        serving_weight_g = float(row[_COL_SERVING_WEIGHT_G] or 0)
        total_weight_g = serving_qty * serving_weight_g

        if food_name == "Quick Add":
            logger.warning(
                "Row %d: 'Quick Add' entry skipped for micro analysis "
                "(no food name to look up).",
                row_idx,
            )

        entries.append(FoodEntry(
            date=str(row[_COL_DATE] or ""),
            time=str(row[_COL_TIME] or ""),
            food_name=food_name,
            serving_size=str(row[_COL_SERVING_SIZE] or ""),
            serving_qty=serving_qty,
            serving_weight_g=serving_weight_g,
            total_weight_g=total_weight_g,
            calories_kcal=float(row[_COL_CALORIES] or 0),
            protein_g=float(row[_COL_PROTEIN] or 0),
            fat_g=float(row[_COL_FAT] or 0),
            carbs_g=float(row[_COL_CARBS] or 0),
        ))

    wb.close()
    return entries


def extract_unique_foods(entries: list[FoodEntry]) -> list[str]:
    """Extract sorted list of unique food names from parsed entries."""
    return sorted({e["food_name"] for e in entries})


def generate_food_mappings(
    foods: list[str],
    existing_mappings: dict[str, str],
    output_path: str,
) -> bool:
    """Generate or merge food_mappings.yaml.

    Only foods with valid non-empty mappings are saved.
    Returns True if the file was created or updated, False if it was already up to date.
    """
    merged: dict[str, str] = {}
    for food in sorted(foods):
        if food in existing_mappings and existing_mappings[food] and str(existing_mappings[food]).strip():
            merged[food] = str(existing_mappings[food]).strip()

    # Also preserve any existing non-empty mappings not in the current food list
    for food, mapping in existing_mappings.items():
        if food not in merged and mapping and str(mapping).strip():
            merged[food] = str(mapping).strip()

    if os.path.exists(output_path):
        try:
            with open(output_path) as f:
                existing_file_data = yaml.safe_load(f)
            if isinstance(existing_file_data, dict) and existing_file_data.get("mappings") == merged:
                return False
        except Exception:
            pass

    data = {
        "mappings": merged,
    }

    header = (
        "# Generated by: python -m omni_pilot import\n"
        "# Contains USDA-searchable English names for each food.\n"
        "# Set to \"skip\" for foods to exclude from micro analysis.\n\n"
    )

    parent = os.path.dirname(output_path)
    if parent:
        os.makedirs(parent, exist_ok=True)

    with open(output_path, "w") as f:
        f.write(header)
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    return True

